version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: library
      POSTGRES_MAX_CONNECTIONS: 200
    ports:
      - "5432:5432"
    networks:
      - test_network
    volumes:
      - ./initDB.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - test_network
    ports:
      - "5000:5000"

networks:
  test_network:
    driver: bridge
