version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: library
      PGPORT: 5432
    ports:
      - "5432:5432"
    networks:
      - test_network
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - test_network
    ports:
      - "5000:5000"
    volumes:
      - ./allure-results:/src/app/bin/Release/net8.0/allure-results

networks:
  test_network:
    driver: bridge
