version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Host=localhost; Database=library; Username=postgres; Password=adminadmin
      - DB=0.0.0.0:5432
    depends_on:
      - db
    networks:
      - test_network
    # ports:
    #   - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
