version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Host=localhost; Database=library; Username=postgres; Password=adminadmin
    depends_on:
      - db
    # ports:
    #   - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: library
