name: .NET CI/CD with Docker

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: dotnet restore ./src/LibraryApp.csproj

      - name: Build
        run: dotnet build ./src/LibraryApp.csproj --no-restore

      # - name: Build Docker Image
      #   run: docker build -t augustvulpes/libraryapp -f docker/Dockerfile

      # - name: Build and push Docker images
      #   run: |
      #     docker-compose build
      #     docker-compose up --abort-on-container-exit --exit-code-from app
          
      # - name: Save test results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: '**/*.trx'
