name: .NET CI/CD with Docker

on:
  workflow_dispatch:


jobs:
  buildAndTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # - name: Dockerfile run
      #   run: docker build -t augustvulpes/libraryapp .

      - name: Docker run 
        run: docker compose up

      # - name: Install dependencies
      #   run: dotnet restore ./src/LibraryApp.csproj

      # - name: Build
      #   run: dotnet build ./src/LibraryApp.csproj --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test ./src/LibraryApp.csproj --no-build